# -*- coding: utf-8 -*-
"""Stock Price Prediction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tT855Ar5iCkmRu7NnEmRZ2hwaczmCuu

# Stock Price prediction using Facebook Prophet 

---

## Importing all the necessary Libraries
"""

#Necessary libraries = Pandas, fbprophet and plotly

#pandas= data Manipulation and analysis
#fbprophet = Forecasting
#plotly= data visualization

import pandas as pd
import plotly.express as px
from fbprophet import Prophet
import matplotlib.pyplot as plt

import seaborn as sb

#Initializing Plotly
 import plotly.io as pio
 pio.renderers.default='colab'

"""## Importing the Dataset & Exploring it"""

df = pd.read_csv("CROMPTON.NS.csv")

#read_csv function from pandas

df

df.info()

df.describe()

"""# Data Visualization using plotly express- Visualizing the historical performance"""

#Line graph, Area graph , box plot (Analyzing price and volume)

px.area(df, x="Date", y="Close")

px.line(df, x="Date", y="Close")

px.area(df, x="Date", y="Volume")

px.bar(df, y="Volume")

px.box(df, y="Close")

plt.plot(df.Date,df.Close)
plt.show()

dataplot = sb.heatmap(df.corr())

"""# Understanding Facebook Prophet

## Data Preperation
"""

df

columns=["Date","Close"]
  ndf = pd.DataFrame(df, columns=columns)

ndf

prophet_df= ndf.rename(columns={'Date':'ds','Close':'y'})

prophet_df

"""## Creating Facebook Prophet Model"""

m = Prophet()
m.fit(prophet_df)

"""##Forecasting"""

future = m.make_future_dataframe(periods=364)
forecast = m.predict(future)

forecast

px.line(forecast, x= 'ds', y='yhat')

figure = m.plot(forecast, xlabel='ds', ylabel='y')

figure2 = m.plot_components(forecast)

"""##Downloading the Forecast data"""

from google.colab import files
forecast.to_csv('forecast.csv')
files.download('forecast.csv')

